apiVersion: v1
kind: Secret
metadata:
  name: pengovr-secrets
  namespace: pengovr
type: Opaque
stringData:
  # Redisのパスワード
  redis-password: pengovr-password
  # SeaweedFS (S3) のアクセスキー
  access-key: pengovr-admin
  secret-key: pengovr-password
